version: '2'
services:
    my-awesome-app-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        command: mongos --configdb my-awesome-app-mongodb-config
    my-awesome-app-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    my-awesome-app-mongodb-config:
        image: mongo:3.6.3
        container_name: my-awesome-app-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
