version: '2'
services:
    my-awesome-app-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/my-awesome-app/mongodb/:/data/db/
